-- MySQL Script generated by MySQL Workbench
-- Mon Oct 19 19:54:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u678836941_sps
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u678836941_sps` ;

-- -----------------------------------------------------
-- Schema u678836941_sps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u678836941_sps` DEFAULT CHARACTER SET utf8 ;
USE `u678836941_sps` ;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`domicilio` (
  `id_domicilio` INT NOT NULL AUTO_INCREMENT,
  `localidad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `piso` INT NULL,
  `departamento` VARCHAR(45) NULL,
  `gmap` VARCHAR(200) NULL,
  `telefono` VARCHAR(45) NULL,
  `referencia_util` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `partido` VARCHAR(45) NULL,
  PRIMARY KEY (`id_domicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`tipo_vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`tipo_vivienda` (
  `id_tipo_vivienda` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_vivienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`clasificacion` (
  `id_clasificacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_clasificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`vivienda` (
  `id_vivienda` INT NOT NULL AUTO_INCREMENT,
  `accesibilidad` VARCHAR(45) NULL,
  `propietario` VARCHAR(45) NULL,
  `inquilino` VARCHAR(45) NULL,
  `importe_alquiler` INT NULL,
  `ambientes` VARCHAR(3) NULL,
  `id_tipo_vivienda` INT NOT NULL,
  `aspecto_interior` INT NOT NULL,
  `aspecto_exterior` INT NOT NULL,
  PRIMARY KEY (`id_vivienda`),
  CONSTRAINT `fk_vivienda_tipo_vivienda1`
    FOREIGN KEY (`id_tipo_vivienda`)
    REFERENCES `u678836941_sps`.`tipo_vivienda` (`id_tipo_vivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vivienda_clasificacion1`
    FOREIGN KEY (`aspecto_interior`)
    REFERENCES `u678836941_sps`.`clasificacion` (`id_clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vivienda_clasificacion2`
    FOREIGN KEY (`aspecto_exterior`)
    REFERENCES `u678836941_sps`.`clasificacion` (`id_clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`informacion_socioambiental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`informacion_socioambiental` (
  `id_informacion_socioambiental` INT NOT NULL AUTO_INCREMENT,
  `id_domicilio` INT NULL,
  `id_vivienda` INT NULL,
  PRIMARY KEY (`id_informacion_socioambiental`),
  CONSTRAINT `fk_informacion_socioambiental_domicilio1`
    FOREIGN KEY (`id_domicilio`)
    REFERENCES `u678836941_sps`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informacion_socioambiental_vivienda1`
    FOREIGN KEY (`id_vivienda`)
    REFERENCES `u678836941_sps`.`vivienda` (`id_vivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`concepto_vecinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`concepto_vecinal` (
  `id_concepto_vecinal` INT NOT NULL AUTO_INCREMENT,
  `nombre_apellido` VARCHAR(50) NULL,
  `afinidad` VARCHAR(50) NULL,
  `tipo_de_amistades` VARCHAR(50) NULL,
  `problemas_policiales` VARCHAR(50) NULL,
  `problemas_economicos` VARCHAR(50) NULL,
  `tiempo_que_conoce` VARCHAR(50) NULL,
  `domicilio` VARCHAR(50) NULL,
  `id_informacion_socioambiental` INT NOT NULL,
  `concepto_del_entrevistado` INT NOT NULL,
  PRIMARY KEY (`id_concepto_vecinal`),
  CONSTRAINT `fk_concepto_vecinal_informacion_socioambiental1`
    FOREIGN KEY (`id_informacion_socioambiental`)
    REFERENCES `u678836941_sps`.`informacion_socioambiental` (`id_informacion_socioambiental`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concepto_vecinal_clasificacion1`
    FOREIGN KEY (`concepto_del_entrevistado`)
    REFERENCES `u678836941_sps`.`clasificacion` (`id_clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`vehiculo_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`vehiculo_tipo` (
  `id_vehiculo_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_vehiculo_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`movilidad_propia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`movilidad_propia` (
  `id_movilidad_propia` INT NOT NULL AUTO_INCREMENT,
  `id_vehiculo_tipo` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `anio` INT NULL,
  `titular` VARCHAR(45) NULL,
  `patente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_movilidad_propia`),
  CONSTRAINT `fk_movilidad_propia_vehiculo_tipo1`
    FOREIGN KEY (`id_vehiculo_tipo`)
    REFERENCES `u678836941_sps`.`vehiculo_tipo` (`id_vehiculo_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`informacion_economica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`informacion_economica` (
  `id_informacion_economica` INT NOT NULL AUTO_INCREMENT,
  `id_movilidad_propia` INT NOT NULL,
  PRIMARY KEY (`id_informacion_economica`),
  CONSTRAINT `fk_informacion_economica_movilidad_propia1`
    FOREIGN KEY (`id_movilidad_propia`)
    REFERENCES `u678836941_sps`.`movilidad_propia` (`id_movilidad_propia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`cuenta_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`cuenta_bancaria` (
  `id_cuenta_bancaria` INT NOT NULL AUTO_INCREMENT,
  `entidad` VARCHAR(45) NULL,
  `id_informacion_economica` INT NOT NULL,
  PRIMARY KEY (`id_cuenta_bancaria`),
  CONSTRAINT `fk_cuenta_bancaria_informacion_economica1`
    FOREIGN KEY (`id_informacion_economica`)
    REFERENCES `u678836941_sps`.`informacion_economica` (`id_informacion_economica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`estado_civil` (
  `id_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`sexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`postulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`postulante` (
  `id_postulante` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_de_nacimiento` DATE NULL,
  `licencia_conductor` VARCHAR(45) NULL,
  `lugar_nacimiento` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `dni` INT NULL,
  `licencia_categoria` VARCHAR(45) NULL,
  `expedida_por_B` VARCHAR(45) NULL,
  `id_estado_civil` INT NULL,
  `id_informacion_socioambiental` INT NULL,
  `id_informacion_economica` INT NULL,
  `id_sexo` INT NULL,
  `profesion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_postulante`),
  CONSTRAINT `fk_postulante_estado_civil1`
    FOREIGN KEY (`id_estado_civil`)
    REFERENCES `u678836941_sps`.`estado_civil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulante_informacion_socioambiental1`
    FOREIGN KEY (`id_informacion_socioambiental`)
    REFERENCES `u678836941_sps`.`informacion_socioambiental` (`id_informacion_socioambiental`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulante_informacion_economica1`
    FOREIGN KEY (`id_informacion_economica`)
    REFERENCES `u678836941_sps`.`informacion_economica` (`id_informacion_economica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulante_sexo1`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `u678836941_sps`.`sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_sexo` INT NOT NULL,
  `e_mail` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_sexo1`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `u678836941_sps`.`sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`entrevista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`entrevista` (
  `id_entrevista` INT NOT NULL AUTO_INCREMENT,
  `id_postulante` INT NOT NULL,
  `organizacion` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `fecha_hora` DATETIME NULL,
  `informacion_relevante` VARCHAR(100) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_entrevista`, `id_postulante`),
  CONSTRAINT `fk_entrevista_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrevista_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `u678836941_sps`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`nivel_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`nivel_estudio` (
  `id_nivel_estudio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_nivel_estudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`estudios` (
  `id_estudios` INT NOT NULL AUTO_INCREMENT,
  `organizacion` VARCHAR(45) NULL,
  `id_postulante` INT NOT NULL,
  `id_nivel_estudio` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `desde` INT NULL,
  `hasta` INT NULL,
  `situacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estudios`),
  CONSTRAINT `fk_estudios_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudios_nivel_estudio1`
    FOREIGN KEY (`id_nivel_estudio`)
    REFERENCES `u678836941_sps`.`nivel_estudio` (`id_nivel_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`familiar_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`familiar_tipo` (
  `id_familiar_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_familiar_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`familiar_postulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`familiar_postulante` (
  `id_familiar_postulante` INT NOT NULL AUTO_INCREMENT,
  `apellido_nombre` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  `profesion` VARCHAR(45) NULL,
  `id_postulante` INT NOT NULL,
  `id_familiar_tipo` INT NOT NULL,
  PRIMARY KEY (`id_familiar_postulante`),
  CONSTRAINT `fk_familiar_postulante_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familiar_postulante_familiar_tipo1`
    FOREIGN KEY (`id_familiar_tipo`)
    REFERENCES `u678836941_sps`.`familiar_tipo` (`id_familiar_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`pregunta` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(250) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`hobbies_pasatiempos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`hobbies_pasatiempos` (
  `id_postulante` INT NOT NULL,
  `id_pregunta` INT NOT NULL,
  `respuesta` VARCHAR(300) NULL,
  PRIMARY KEY (`id_postulante`, `id_pregunta`),
  CONSTRAINT `fk_hobbies_pasatiempos_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hobbies_pasatiempos_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `u678836941_sps`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`idioma_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`idioma_tipo` (
  `id_idioma_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_idioma_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`clasificacion_idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`clasificacion_idioma` (
  `id_clasificacion_idioma` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_clasificacion_idioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`idioma` (
  `id_idioma` INT NOT NULL AUTO_INCREMENT,
  `id_postulante` INT NOT NULL,
  `id_idioma_tipo` INT NOT NULL,
  `lee` INT NOT NULL,
  `habla` INT NOT NULL,
  `escribe` INT NOT NULL,
  PRIMARY KEY (`id_idioma`, `id_postulante`, `id_idioma_tipo`),
  CONSTRAINT `fk_idioma_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idioma_idioma_tipo1`
    FOREIGN KEY (`id_idioma_tipo`)
    REFERENCES `u678836941_sps`.`idioma_tipo` (`id_idioma_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idioma_clasificacion_idioma1`
    FOREIGN KEY (`lee`)
    REFERENCES `u678836941_sps`.`clasificacion_idioma` (`id_clasificacion_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idioma_clasificacion_idioma2`
    FOREIGN KEY (`habla`)
    REFERENCES `u678836941_sps`.`clasificacion_idioma` (`id_clasificacion_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idioma_clasificacion_idioma3`
    FOREIGN KEY (`escribe`)
    REFERENCES `u678836941_sps`.`clasificacion_idioma` (`id_clasificacion_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '																	';

-- -----------------------------------------------------
-- Table `u678836941_sps`.`informe_confidencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`informe_confidencial` (
  `id_postulante` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `respuesta` VARCHAR(200) NULL,
  PRIMARY KEY (`id_postulante`),
  CONSTRAINT `fk_informe_confidencial_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_confidencial_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `u678836941_sps`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`referencias_laborales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`referencias_laborales` (
  `id_referencias_laborales` INT NOT NULL AUTO_INCREMENT,
  `id_postulante` INT NOT NULL,
  `empresa` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  `desde` VARCHAR(45) NULL,
  `hasta` VARCHAR(45) NULL,
  PRIMARY KEY (`id_referencias_laborales`),
  CONSTRAINT `fk_referencias_laborales_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`informe_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`informe_laboral` (
  `id_informe_laboral` INT NOT NULL AUTO_INCREMENT,
  `id_referencias_laborales` INT NOT NULL,
  `puesto_al_ingresar` VARCHAR(45) NULL DEFAULT '',
  `ultimo_puesto_ocupado` VARCHAR(45) NULL DEFAULT '',
  `causa_de_egreso` VARCHAR(45) NULL DEFAULT '',
  `asistencia` VARCHAR(45) NULL DEFAULT '',
  `puntualidad` VARCHAR(45) NULL DEFAULT '',
  `concepto_general` VARCHAR(45) NULL DEFAULT '',
  PRIMARY KEY (`id_informe_laboral`),
  CONSTRAINT `fk_informe_laboral_referencias_laborales1`
    FOREIGN KEY (`id_referencias_laborales`)
    REFERENCES `u678836941_sps`.`referencias_laborales` (`id_referencias_laborales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`informe_laboral_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`informe_laboral_pregunta` (
  `id_informe_laboral` INT NOT NULL,
  `id_pregunta_laboral` INT NOT NULL,
  `respuesta` VARCHAR(200) NULL,
  PRIMARY KEY (`id_informe_laboral`, `id_pregunta_laboral`),
  CONSTRAINT `fk_informe_laboral_pregunta_informe_laboral1`
    FOREIGN KEY (`id_informe_laboral`)
    REFERENCES `u678836941_sps`.`informe_laboral` (`id_informe_laboral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_laboral_pregunta_pregunta1`
    FOREIGN KEY (`id_pregunta_laboral`)
    REFERENCES `u678836941_sps`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`observaciones_convivencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`observaciones_convivencia` (
  `id_observaciones_convivencia` INT NOT NULL AUTO_INCREMENT,
  `observacion` VARCHAR(300) NULL,
  `id_postulante` INT NOT NULL,
  PRIMARY KEY (`id_observaciones_convivencia`),
  CONSTRAINT `fk_observaciones_convivencia_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`observaciones_infolaboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`observaciones_infolaboral` (
  `id_observaciones_infolaboral` INT NOT NULL AUTO_INCREMENT,
  `observacion` VARCHAR(300) NULL,
  `id_postulante` INT NOT NULL,
  PRIMARY KEY (`id_observaciones_infolaboral`),
  CONSTRAINT `fk_observaciones_infolaboral_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`tarjeta_credito_debito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`tarjeta_credito_debito` (
  `id_tarjeta_credito_debito` INT NOT NULL AUTO_INCREMENT,
  `id_informacion_economica` INT NOT NULL,
  `otras_propiedades` VARCHAR(45) NULL,
  `seguro_de_vida` VARCHAR(45) NULL,
  `prendas` VARCHAR(45) NULL,
  `observaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`id_tarjeta_credito_debito`),
  CONSTRAINT `fk_tarjeta_credito_debito_informacion_economica1`
    FOREIGN KEY (`id_informacion_economica`)
    REFERENCES `u678836941_sps`.`informacion_economica` (`id_informacion_economica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`tarjeta_entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`tarjeta_entidad` (
  `id_tarjeta_entidad` INT NOT NULL AUTO_INCREMENT,
  `id_tarjeta_credito_debito` INT NOT NULL,
  `tarjeta` VARCHAR(45) NULL,
  `entidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tarjeta_entidad`),
  CONSTRAINT `fk_tarjeta_entidad_tarjeta_credito_debito1`
    FOREIGN KEY (`id_tarjeta_credito_debito`)
    REFERENCES `u678836941_sps`.`tarjeta_credito_debito` (`id_tarjeta_credito_debito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`transporte_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`transporte_tipo` (
  `id_transporte_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_transporte_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`transporte` (
  `id_transporte` INT NOT NULL AUTO_INCREMENT,
  `cuadras` VARCHAR(45) NULL,
  `id_transporte_tipo` INT NOT NULL,
  `id_domicilio` INT NOT NULL,
  PRIMARY KEY (`id_transporte`),
  CONSTRAINT `fk_transporte_transporte_tipo1`
    FOREIGN KEY (`id_transporte_tipo`)
    REFERENCES `u678836941_sps`.`transporte_tipo` (`id_transporte_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transporte_domicilio1`
    FOREIGN KEY (`id_domicilio`)
    REFERENCES `u678836941_sps`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`servicio` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u678836941_sps`.`conyuge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`conyuge` (
  `id_conyuge` INT NOT NULL AUTO_INCREMENT,
  `id_postulante` INT NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `id_sexo` INT NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `dni` INT NULL,
  `lugar_nacimiento` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `profesion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_conyuge`, `id_postulante`),
  CONSTRAINT `fk_conyuge_sexo1`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `u678836941_sps`.`sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conyuge_postulante1`
    FOREIGN KEY (`id_postulante`)
    REFERENCES `u678836941_sps`.`postulante` (`id_postulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u678836941_sps`.`vivienda_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u678836941_sps`.`vivienda_servicio` (
  `id_servicio` INT NOT NULL,
  `id_vivienda` INT NOT NULL,
  PRIMARY KEY (`id_servicio`, `id_vivienda`),
  CONSTRAINT `fk_servicio_has_vivienda_servicio1`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `u678836941_sps`.`servicio` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_has_vivienda_vivienda1`
    FOREIGN KEY (`id_vivienda`)
    REFERENCES `u678836941_sps`.`vivienda` (`id_vivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`tipo_vivienda`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`tipo_vivienda` (`id_tipo_vivienda`, `descripcion`) VALUES (1, 'Material');
INSERT INTO `u678836941_sps`.`tipo_vivienda` (`id_tipo_vivienda`, `descripcion`) VALUES (2, 'Prefabricada');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`clasificacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`clasificacion` (`id_clasificacion`, `descripcion`) VALUES (1, 'Muy Bueno');
INSERT INTO `u678836941_sps`.`clasificacion` (`id_clasificacion`, `descripcion`) VALUES (2, 'Bueno');
INSERT INTO `u678836941_sps`.`clasificacion` (`id_clasificacion`, `descripcion`) VALUES (3, 'Regular');
INSERT INTO `u678836941_sps`.`clasificacion` (`id_clasificacion`, `descripcion`) VALUES (4, 'Malo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`vehiculo_tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`vehiculo_tipo` (`id_vehiculo_tipo`, `descripcion`) VALUES (1, 'Automovil');
INSERT INTO `u678836941_sps`.`vehiculo_tipo` (`id_vehiculo_tipo`, `descripcion`) VALUES (2, 'Moto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`estado_civil`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`estado_civil` (`id_estado_civil`, `descripcion`, `tipo`) VALUES (1, 'Soltero/a', NULL);
INSERT INTO `u678836941_sps`.`estado_civil` (`id_estado_civil`, `descripcion`, `tipo`) VALUES (3, 'Casado/a', NULL);
INSERT INTO `u678836941_sps`.`estado_civil` (`id_estado_civil`, `descripcion`, `tipo`) VALUES (5, 'Concubino/a', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`sexo`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`sexo` (`id_sexo`, `descripcion`) VALUES (1, 'Masculino');
INSERT INTO `u678836941_sps`.`sexo` (`id_sexo`, `descripcion`) VALUES (2, 'Femenino');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`usuario` (`id_usuario`, `nombre`, `id_sexo`, `e_mail`, `contrasenia`, `nombre_usuario`, `apellido`) VALUES (1, 'pablo', 1, 'berto', '1234', 'berto', 'berto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`nivel_estudio`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`nivel_estudio` (`id_nivel_estudio`, `descripcion`) VALUES (1, 'Primario');
INSERT INTO `u678836941_sps`.`nivel_estudio` (`id_nivel_estudio`, `descripcion`) VALUES (2, 'Secundario');
INSERT INTO `u678836941_sps`.`nivel_estudio` (`id_nivel_estudio`, `descripcion`) VALUES (3, 'Terciario');
INSERT INTO `u678836941_sps`.`nivel_estudio` (`id_nivel_estudio`, `descripcion`) VALUES (4, 'Universitario');
INSERT INTO `u678836941_sps`.`nivel_estudio` (`id_nivel_estudio`, `descripcion`) VALUES (5, 'Otros');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`familiar_tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`familiar_tipo` (`id_familiar_tipo`, `descripcion`) VALUES (1, 'Padre');
INSERT INTO `u678836941_sps`.`familiar_tipo` (`id_familiar_tipo`, `descripcion`) VALUES (2, 'Madre');
INSERT INTO `u678836941_sps`.`familiar_tipo` (`id_familiar_tipo`, `descripcion`) VALUES (3, 'Hijo');
INSERT INTO `u678836941_sps`.`familiar_tipo` (`id_familiar_tipo`, `descripcion`) VALUES (4, 'Hija');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`pregunta`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`pregunta` (`id_pregunta`, `pregunta`, `tipo`) VALUES (1, 'Pregunta hp', 'hp');
INSERT INTO `u678836941_sps`.`pregunta` (`id_pregunta`, `pregunta`, `tipo`) VALUES (2, 'Pregunta ic', 'ic');
INSERT INTO `u678836941_sps`.`pregunta` (`id_pregunta`, `pregunta`, `tipo`) VALUES (3, 'Pregunta pl', 'pl');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`idioma_tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`idioma_tipo` (`id_idioma_tipo`, `descripcion`) VALUES (1, 'Ingles');
INSERT INTO `u678836941_sps`.`idioma_tipo` (`id_idioma_tipo`, `descripcion`) VALUES (2, 'Portugues');
INSERT INTO `u678836941_sps`.`idioma_tipo` (`id_idioma_tipo`, `descripcion`) VALUES (3, 'Frances');
INSERT INTO `u678836941_sps`.`idioma_tipo` (`id_idioma_tipo`, `descripcion`) VALUES (4, 'Otros');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`clasificacion_idioma`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`clasificacion_idioma` (`id_clasificacion_idioma`, `descripcion`) VALUES (1, 'Bien');
INSERT INTO `u678836941_sps`.`clasificacion_idioma` (`id_clasificacion_idioma`, `descripcion`) VALUES (2, 'Regular');
INSERT INTO `u678836941_sps`.`clasificacion_idioma` (`id_clasificacion_idioma`, `descripcion`) VALUES (3, 'Muy Bien');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`transporte_tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`transporte_tipo` (`id_transporte_tipo`, `descripcion`) VALUES (1, 'Colectivo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u678836941_sps`.`servicio`
-- -----------------------------------------------------
START TRANSACTION;
USE `u678836941_sps`;
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (1, 'Luz');
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (2, 'Gas');
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (3, 'Agua Corriente');
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (4, 'Telefono');
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (5, 'TV por Cable');
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (6, 'Cloacas');
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (7, 'Pavimento');
INSERT INTO `u678836941_sps`.`servicio` (`id_servicio`, `descripcion`) VALUES (8, 'Vigilancia Privada');

COMMIT;

